name: sablesargasses
description: "Envie de plage? D'abord, check!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_native_splash: ^2.4.1

  # CORE
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  shared_preferences: ^2.3.0
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash_icon.png
    - assets/app_icon.png
    - assets/beach.jpg
    - assets/images/
    - assets/images/placeholder_beach.jpg
    - assets/images/anse-bertrand---plage-de-la-chapelle-min.jpg
    - assets/images/bouillante---plage-de-malendure-min.jpg
    - assets/images/deshaies---plage-de-la-grande-anse-min.jpg
    - assets/images/deshaies---plage-de-la-perle-min.jpg
    - assets/images/gosier---plage-de-la-datcha-min.jpg
    - assets/images/gosier---plage-ilet-du-gosier-min.jpg
    - assets/images/la-desirade---plage-a-fifi-min.jpg
    - assets/images/le-moule---plage-de-l'autre-bord-min.jpg
    - assets/images/les-saintes---plage-du-pain-de-sucre-min.jpg
    - assets/images/marie-galante---plage-de-la-feuillere-min.jpg
    - assets/images/port-louis---plage-du-souffleur-min.jpg
    - assets/images/ste-anne---plage-de-la-caravelle-min.jpg
    - assets/images/ste-anne---plage-du-bourg-min.jpg
    - assets/images/ste-rose---plage-de-cluny-min.jpg
    - assets/images/st-franÃ§ois---plage-des-raisins-clairs-min.jpg